### ISSUE TITLE
SuperExcelente!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-patriciaSR#1]
Buen trabajo @patriciaSR  !

1 pista para dejarlo fetén del todo:

- [x] Revisa los metadatos en index.html (lang, title...)

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by patriciaSR** [comment]
Revisado y actualizado en master!!! :bowtie:
He añadido como "extra" un iconito de una pokeball al title de la página :wink:
Los bonus están en camino pero los terminaré el finde para aprovechar y así hacer un super repaso de todo.

Muchas gracias por los tips!!! :blush:

**Comment by oneeyedman** [comment]
Muy buen trabajo, Patricia!!
